
services:
  nginx:
    build: nginx
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "833:443"
    volumes:
      - nginx:/usr/share/nginx/
      - php_code:/var/www/php
  php:
    build: ./php
    expose:
      - 9000
    volumes:
      - php_code:/var/www/php

volumes:
  nginx:
    name: nginx-volumes
    driver: local
    driver_opts:
      type: none
      device: ./front
      o: bind
  php_code:
    name: php-volumes
    driver: local
    driver_opts:
      type: none
      device: ./php/code
      o: bind