server {  
 listen 443 ssl;  
 server_name localhost;
 ssl_certificate /etc/ssl/certs/camagru.crt;
 ssl_certificate_key /etc/ssl/private/camagru.key;
 ssl_protocols TLSv1.2 TLSv1.3;
 
  
 root /usr/share/nginx/html;  
 index index.html index.php;  
 
 location / {
  try_files $uri /index.html;
 }
}